export const GOOGLE_PUBSUB_SUBSCRIPTION_MESSAGE_EVENT = 'message';
export const GOOGLE_PUBSUB_CLIENT_TOKEN = 'GOOGLE_PUBSUB_INSTANCE_TOKEN';
export const GOOGLE_PUBSUB_MODULE_OPTIONS = 'GOOGLE_PUBSUB_MODULE_OPTIONS';
